### PR TITLE
Ensure packer to provision EC2 instance with imdsv2 enabled

### PR DESCRIPTION
**Pull request by peterzhuamazon**
### Description
Ensure packer to provision EC2 instance with imdsv2 enabled
Note that this will not make the AMI itself to be imdsv2 only
We currently still maintain the ability for AMI to be both imdsv1 and imdsv2, and use Jenkins EC2 plugin to enforce the imdsv2 during provision of agents.

Thanks.

### Issues Resolved
https://github.com/opensearch-project/opensearch-ci/issues/435

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by peterzhuamazon** [comment]
Tested on beta jenkins account and we do not need to rebuild, due to this will only affect the AMI build process, not AMI itself.

Thanks.

**Review by gaiksaya — APPROVED** [review]
Please keep watch of hop_limit. Mostly wont take have effect since this is for EC2 building the AMI

**Comment by peterzhuamazon** [comment]
> Please keep watch of hop_limit. Mostly wont take have effect since this is for EC2 building the AMI

Yes, have tested to build within a docker, and still runs fine as the connection is just initialized from docker -> EC2.

**Comment by peterzhuamazon** [comment]
Waiting for:
* https://github.com/opensearch-project/opensearch-ci/pull/439

**Pull request merged**
