### PR TITLE
Install pigz and unpigz to speed up docker image extraction

### PR DESCRIPTION
**Pull request by peterzhuamazon**
### Description
Install pigz and unpigz to speed up docker image extraction

### Issues Resolved
Closes https://github.com/opensearch-project/opensearch-ci/issues/374

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by peterzhuamazon** [comment]
Have double verify that pigz will also install unpigz.

**Review by gaiksaya — APPROVED** [review]
Do we need this package on windows as well? To full the images faster?

**Comment by prudhvigodithi** [comment]
Thanks, just installing `pigz` would take care of parallel docker extraction?  I'm curious why `docker` dont directly install it as pre-req. :)

**Comment by peterzhuamazon** [comment]
> Do we need this package on windows as well? To full the images faster?

It is already on Windows and reduced time from 15-20min to 12min 😄

**Comment by peterzhuamazon** [comment]
> Thanks, just installing `pigz` would take care of parallel docker extraction? I'm curious why `docker` dont directly install it as pre-req. :)

Yes, there is a long history of thread to get pigz/unpigz support in docker.
As of now, docker build is still single thread and docker pull/extraction can support unpigz if detected in path.
The thing is docker maintainers seems still thinking parallelism can cause trouble between, thus not suggesting it by default. Thanks.

**Pull request merged**
