### PR TITLE
Restore old windows runner for gradle and update jdk21

### PR DESCRIPTION
**Pull request by peterzhuamazon**
### Description
Restore old windows runner for gradle and update jdk21

### Issues Resolved
https://github.com/opensearch-project/opensearch-build/issues/3816

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by reta — APPROVED** [review]

**Review by rishabh6788 — APPROVED** [review]

**Comment by peterzhuamazon** [comment]
https://build.ci.opensearch.org/job/packer-build/81/console

**Comment by peterzhuamazon** [comment]
https://build.ci.opensearch.org/job/packer-build/82/console

**Comment by peterzhuamazon** [comment]
https://github.com/adoptium/temurin/issues/9

**Comment by peterzhuamazon** [comment]
https://build.ci.opensearch.org/job/packer-build/90/console

**Pull request merged**
