### PR TITLE
[NodeJS18 Upgrade] Remove old AL2 Docker Host and Tweak Windows Startup Scripts

### PR DESCRIPTION
**Pull request by peterzhuamazon**
### Description
[NodeJS18 Upgrade] Remove old AL2 Docker Host and Tweak Windows Startup Scripts

### Issues Resolved
https://github.com/opensearch-project/opensearch-build/issues/1563
https://github.com/opensearch-project/opensearch-build/issues/3743

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by jordarlu — APPROVED** [review]

**Review by rishabh6788 — APPROVED** [review]

**Review by gaiksaya — CHANGES_REQUESTED** [review]
The host is being used by client release process: https://github.com/opensearch-project/opensearch-build-libraries/blob/main/vars/standardReleasePipelineWithGenericTrigger.groovy#L30

**Comment by gaiksaya** [comment]
Please do not remove host. They can be used by multiple projects outside opensearch-build scope. `enkins-Agent-AL2-X64-C54xlarge-Docker-Host` is atleast vastly in use for now.
Thanks!

**Comment by peterzhuamazon** [comment]
> Please do not remove host. They can be used by multiple projects outside opensearch-build scope. `Jenkins-Agent-AL2-X64-C54xlarge-Docker-Host` is atleast vastly in use for now. We can add new ones but old ones should not be removed prior to heads-up or warning for atleast few months. Thanks!

I didnt realize they are still being used by clients.
I am ok to restore them but we still need to remove them at some time.

Thanks.

**Review by gaiksaya — APPROVED** [review]

**Comment by peterzhuamazon** [comment]
https://build.ci.opensearch.org/job/packer-build/67/console

**Pull request merged**
