### PR TITLE
Blueocean plugin install

### PR DESCRIPTION
**Pull request by prudhvigodithi**
### Description
Blueocean plugin install.

### Issues Resolved
https://github.com/opensearch-project/opensearch-ci/issues/195

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by gaiksaya** [comment]
Does it work as expected? did you try installing in your dev environment? Wanted to make sure it is not affecting any other plugin config and installation goes through. 
Thanks!

**Comment by prudhvigodithi** [comment]
> Does it work as expected? did you try installing in your dev environment? Wanted to make sure it is not affecting any other plugin config and installation goes through.
> Thanks!

From the document as it says, it doesnot, however the image needs to be build that contains the blueocean plugin, I will update here with some tests with my own image.

**Comment by gaiksaya** [comment]
> > Does it work as expected? did you try installing in your dev environment? Wanted to make sure it is not affecting any other plugin config and installation goes through.
> > Thanks!
> 
> From the document as it says, it doesnot, however the image needs to be build that contains the blueocean plugin, I will update here with some tests with my own image.

Thanks! Yeah I usually try to build the image and try bringing the jenkins up using the same. Will wait for your confirmation. Some plugins break the overall jenkins deployment

**Comment by prudhvigodithi** [comment]
Hey @gaiksaya I have done the basic testing to make sure Jenkins is up and running, image used `1001235258/jenkins:2.332.3-lts-jdk8`, should test on with job data something like on beta before deployed to prod. Also If you any jenkins environment setup ready can you switch the image to `1001235258/jenkins:2.332.3-lts-jdk8` and try to bring the jenkins (just for 2nd pair of eyes).
Thank you

**Comment by gaiksaya** [comment]
> Hey @gaiksaya I have done the basic testing to make sure Jenkins is up and running, image used `1001235258/jenkins:2.332.3-lts-jdk8`, should test on with job data something like on beta before deployed to prod. Also If you any jenkins environment setup ready can you switch the image to `1001235258/jenkins:2.332.3-lts-jdk8` and try to bring the jenkins (just for 2nd pair of eyes). Thank you

Tested it against the new image it takes sometime to load but later its good.

**Review by gaiksaya — APPROVED** [review]

**Pull request merged**
